remote_theme: zendesk/jekyll-theme-zendesk-garden@main
sidebar:
  - label: Machine Learning
    children:
      - intro
      - libraries
      - tools
      - label: Algorithms
        children:
          - linear-regression
  - label: Deep Learning
    children:
      - deep-learning
