title: Deep Dive With Shilpa
description: Learning with simple language and deep dive of each concept is important to learn and digest
markdown: kramdown

# GitHub Pages-compatible
plugins:
  - jekyll-remote-theme
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

# For user/organization site repos (like shilpathota.github.io)
baseurl: ""  # important for links

sidebar:
  - label: Machine Learning
    children:
      - intro
      - libraries
      - tools
      - label: Algorithms
        children:
          - linear-regression
  - label: Deep Learning
    children:
      - deep-learning
  - label: Kubernetes
    children:
      - intro-kube
      - k8s-components
      - k8s-deployment-strategies
