remote_theme: zendesk/jekyll-theme-zendesk-garden@main
sidebar:
  - label: Machine Learning
    children:
      - intro-ml
  - label: Deep Learning
    children:
      - intro-deep
      - label: Optimization
        children:
          - AdaBoost
      - Algorithms
  - label: Kubernetes
    children:
      - Introduction